### ISSUE TITLE
The bandpass module crashes while creating the report

### ISSUE THREAD

**Issue by ziotom78** [lspestrip/striptun#20]
Calculations seem to complete correctly, yet the code crashes with the following error before the report is written:
`````
Traceback (most recent call last):
  File "striptun\bandwidth.py", line 457, in <module>
    main()
  File "striptun\bandwidth.py", line 453, in main
    output_path=args.output_path)
  File "C:\Users\tomasi\Documents\work\LSPE\bicocca\striptun\reports.py", line 69, in create_report
    md_report = report_template.render_unicode(**extended_params)
  File "C:\Users\tomasi\Anaconda3\lib\site-packages\Mako-1.0.7-py3.6.egg\mako\template.py", line 471, in render_unicode
    as_unicode=True)
  File "C:\Users\tomasi\Anaconda3\lib\site-packages\Mako-1.0.7-py3.6.egg\mako\runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "C:\Users\tomasi\Anaconda3\lib\site-packages\Mako-1.0.7-py3.6.egg\mako\runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "C:\Users\tomasi\Anaconda3\lib\site-packages\Mako-1.0.7-py3.6.egg\mako\runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "C__Users_tomasi_Documents_work_LSPE_bicocca_striptun_template_bandwidth_md", line 52, in render_body
TypeError: 'Undefined' object is not subscriptable
`````

**Comment by silviacaprioli** [comment]
fixed with 73eae159b212b073a16a1753f530200ee99da099
