### ISSUE TITLE
Tnoise analysis crashes while producing matrix plots

### ISSUE THREAD

**Issue by ziotom78** [lspestrip/striptun#22]
Running an analysis on test 311 (STRIP04) makes the code crash with the following error message:
`````
Traceback (most recent call last):
  File "striptun\tnoise_step2.py", line 677, in <module>
    main()
  File "striptun\tnoise_step2.py", line 668, in main
    create_plots(log_ln, params, args.output_path)
  File "striptun\tnoise_step2.py", line 577, in create_plots
    create_tnoise_matrix_plot(*args, **kwargs)
  File "striptun\tnoise_step2.py", line 541, in create_tnoise_matrix_plot
    .format(i, cur_det, cur_estimates))
AssertionError: unable to find temperature with index 2 for detector Q2 (PWR3):
[{'detector_idx': 3, 'detector_name': 'Q2 (PWR3)', 'step_1_idx': 0, 'step_2_idx': 3, 'temperature_1': 31.07771875295682, 'temperature_2': 27.723170917416446, 'output_1': -51681.459999999999, 'output_2': -49591.096986491168, 'tnoise': 51.859038480206841, 'gain': -623.14300346595053}, {'detector_idx': 3, 'detector_name': 'Q2 (PWR3)', 'step_1_idx': 0, 'step_2_idx': 4, 'temperature_1': 31.07771875295682, 'temperature_2': 26.602937643029655, 'output_1': -51681.459999999999, 'output_2': -48989.093023255817, 'tnoise': 54.818157603808494, 'gain': -601.67568214035077}, {'detector_idx': 3, 'detector_name': 'Q2 (PWR3)', 'step_1_idx': 1, 'step_2_idx': 4, 'temperature_1': 29.963637466190036, 'temperature_2': 26.602937643029655, 'output_1': -50845.858056265984, 'output_2': -48989.093023255817, 'tnoise': 62.066136436383886, 'gain': -552.49356702857131}]
`````

**Comment by ziotom78** [comment]
The bug is triggered when there is some unbalance in the HEMTs and the «blind» channel is not completely blind. The fix makes the code more tolerant when this kind of situation happens.
